name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    strategy:
      matrix:
        destination:
          - "generic/platform=iOS"
          - "platform=macOS"
          - "generic/platform=visionOS"
          - "generic/platform=tvOS"
    
    steps:
      - uses: actions/checkout@v3
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild test -scheme URLSchemeRouter -destination "${{ matrix.destination }}" | xcbeautify --renderer github-actions
